run:
  timeout: 5m
linters:
  enable:
    - prealloc
    - revive
    - goimports
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
