ENVIRONMENT: local
PORT: 3000
GRPC_PORT: 8087
LOG_LEVEL: debug
DB:
  USER: dimo
  PASSWORD: dimo
  PORT: 5432
  HOST: localhost
  NAME: device_data_api
  MAX_OPEN_CONNECTIONS: 5
  MAX_IDLE_CONNECTIONS: 5
JWT_KEY_SET_URL: https://auth.dev.dimo.zone/keys # dev
#JWT_KEY_SET_URL: http://127.0.0.1:5556/keys # local

AUTO_PI_API_TOKEN:
AUTO_PI_API_URL:

ELASTIC_SEARCH_APP_SEARCH_HOST: https://dimo.ent.us-east-2.aws.elastic-cloud.com
ELASTIC_SEARCH_APP_SEARCH_TOKEN:

ELASTIC_SEARCH_ANALYTICS_HOST: https://dimo.es.us-east-2.aws.elastic-cloud.com
ELASTIC_SEARCH_ANALYTICS_USERNAME: device-analytics
ELASTIC_SEARCH_ANALYTICS_PASSWORD:
DEVICE_DATA_INDEX_NAME: device-status-dev*

IPFS_ADDRESS: localhost:5001

AWS_ACCESS_KEY_ID: access-key
AWS_SECRET_ACCESS_KEY: secret-access-key
AWS_REGION: us-east-2
AWS_BUCKET_NAME: test-bucket
AWS_ENDPOINT: http://localhost.localstack.cloud:4566
MAX_AWS_FILE_SIZE: 2500000000

SERVICE_NAME: users-api
EMAIL_HOST: localhost
EMAIL_PORT: 1025
EMAIL_USERNAME: dimo
EMAIL_PASSWORD: dimo
EMAIL_FROM: mailer@dimo.zone

NATS_URL: http://localhost:4222
NATS_STREAM_NAME: DATA-DOWNLOAD
NATS_DATA_DOWNLOAD_SUBJECT: data-download
NATS_DURABLE_CONSUMER: data-download-durable
NATS_ACK_TIMEOUT: 2m

DEVICE_STATUS_TOPIC: topic.device.status
KAFKA_BROKERS: localhost:9092
EVENTS_TOPIC: topic.event

DEVICES_APIGRPC_ADDR: localhost:8282
DEVICE_DEFINITIONS_GRPC_ADDR: localhost:8283
USERS_API_GRPC_ADDR: localhost:8284

ENABLE_PRIVILEGES: false