ENVIRONMENT: local
PORT: 3000
LOG_LEVEL: debug
JWT_KEY_SET_URL: https://auth.dimo.zone/keys # prod
#JWT_KEY_SET_URL: http://127.0.0.1:5556/keys

ELASTIC_SEARCH_APP_SEARCH_HOST: https://dimo.ent.us-east-2.aws.elastic-cloud.com
ELASTIC_SEARCH_APP_SEARCH_TOKEN:

ELASTIC_SEARCH_ANALYTICS_HOST: https://dimo.es.us-east-2.aws.elastic-cloud.com
ELASTIC_SEARCH_ANALYTICS_USERNAME: device-analytics
ELASTIC_SEARCH_ANALYTICS_PASSWORD:
DEVICE_DATA_INDEX_NAME: device-status-dev*