replicaCount: 4
image:
  repository: dimozone/device-data-api
  pullPolicy: IfNotPresent
  tag: 0.4.27
cronJob:
  enabled: true
  schedule: 0 0 * * 0
env:
  ENVIRONMENT: prod
  PORT: '8080'
  LOG_LEVEL: info
  SERVICE_NAME: device-data-api
  JWT_KEY_SET_URL: https://auth.dimo.zone/keys
  DEPLOYMENT_BASE_URL: https://device-data-api.dimo.zone
  DEVICE_DATA_INDEX_NAME: device-status-prod*
  DEVICES_APIGRPC_ADDR: devices-api-prod:8086
  ENABLE_PRIVILEGES: true
  TOKEN_EXCHANGE_JWK_KEY_SET_URL: http://dex-roles-rights-prod.prod.svc.cluster.local:5556/keys
  VEHICLE_NFT_ADDRESS: '0xba5738a18d83d41847dffbdc6101d37c69c9b0cf'
  DEVICE_DEFINITIONS_GRPC_ADDR: device-definitions-api-prod:8086
  USERS_API_GRPC_ADDR: users-api-prod:8086
  AWS_BUCKET_NAME: dimo-network-device-data-export-prod
  NATS_URL: nats-prod:4222
  KAFKA_BROKERS: kafka-prod-dimo-kafka-kafka-brokers:9092
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: https://app.dimo.zone
    nginx.ingress.kubernetes.io/limit-rps: '9'
    external-dns.alpha.kubernetes.io/hostname: device-data-api.dimo.zone
  hosts:
    - host: device-data-api.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 1
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 1
