{{- range $job := .Values.jobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "device-data-api.fullname" $ }}-{{ $job.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "device-data-api.labels" $ | nindent 4 }}
spec:
  schedule: {{ $job.schedule | quote }}
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
          {{- with $.Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
          {{- end }}
        spec:
          containers:
            - name: device-data-api
              securityContext:
                {{- toYaml $.Values.securityContext | nindent 14 }}
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
              command: ['/bin/sh']
              {{- with $job.args }}
              args:
{{ toYaml . | indent 12 }}
                {{- end }}
              envFrom:
                - configMapRef:
                    name: {{ include "device-data-api.fullname" $ }}-config
                - secretRef:
              name: {{ include "device-data-api.fullname" $ }}-secret
              restartPolicy: OnFailure
{{- end }}
