apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ include "device-data-api.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  backendType: secretsManager
  data:
    - key: {{ .Release.Namespace }}/devices/elastic/analytics/host
      name: ELASTIC_SEARCH_ANALYTICS_HOST
    - key: {{ .Release.Namespace }}/devices/elastic/analytics/username
      name: ELASTIC_SEARCH_ANALYTICS_USERNAME
    - key: {{ .Release.Namespace }}/devices/elastic/analytics/password
      name: ELASTIC_SEARCH_ANALYTICS_PASSWORD
    - key: {{ .Release.Namespace }}/users/email/user
      name: EMAIL_USERNAME
    - key: {{ .Release.Namespace }}/users/email/password
      name: EMAIL_PASSWORD
    - key: {{ .Release.Namespace }}/users/email/host
      name: EMAIL_HOST
    - key: {{ .Release.Namespace }}/data/aws/access_key_id
      name: AWS_ACCESS_KEY_ID
    - key: {{ .Release.Namespace }}/data/aws/secret_access_key
      name: AWS_SECRET_ACCESS_KEY
