apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "device-data-api.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/elastic/analytics/host
    secretKey: ELASTIC_SEARCH_ANALYTICS_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/elastic/analytics/username
    secretKey: ELASTIC_SEARCH_ANALYTICS_USERNAME
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/elastic/analytics/password
    secretKey: ELASTIC_SEARCH_ANALYTICS_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/users/email/user
    secretKey: EMAIL_USERNAME
  - remoteRef:
      key: {{ .Release.Namespace }}/users/email/password
    secretKey: EMAIL_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/users/email/host
    secretKey: EMAIL_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/data/aws/access_key_id
    secretKey: AWS_ACCESS_KEY_ID
  - remoteRef:
      key: {{ .Release.Namespace }}/data/aws/secret_access_key
    secretKey: AWS_SECRET_ACCESS_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/data/db/host
    secretKey: DB_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/data/db/user
    secretKey: DB_USER
  - remoteRef:
      key: {{ .Release.Namespace }}/data/db/pass
    secretKey: DB_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/autopi/management_token
    secretKey: AUTO_PI_API_TOKEN
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/autopi/management_url
    secretKey: AUTO_PI_API_URL
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: {{ include "device-data-api.fullname" . }}-secret
    template:
      metadata: {}
