apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ include "device-data-api.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  backendType: secretsManager
  data:
    - key: {{ .Release.Namespace }}/devices/elastic/appsearch/host
      name: ELASTIC_SEARCH_APP_SEARCH_HOST
    - key: {{ .Release.Namespace }}/devices/elastic/appsearch/token
      name: ELASTIC_SEARCH_APP_SEARCH_TOKEN
    - key: {{ .Release.Namespace }}/devices/elastic/analytics/host
      name: ELASTIC_SEARCH_ANALYTICS_HOST
    - key: {{ .Release.Namespace }}/devices/elastic/analytics/username
      name: ELASTIC_SEARCH_ANALYTICS_USERNAME
    - key: {{ .Release.Namespace }}/devices/elastic/analytics/password
      name: ELASTIC_SEARCH_ANALYTICS_PASSWORD
