// Package docs Code generated by swaggo/swag at 2023-12-06 15:48:30.245122 -0500 EST m=+1.379928626. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/autopi/last-seen/{ethAddr}": {
            "get": {
                "security": [
                    {
                        "PreSharedKey": []
                    }
                ],
                "description": "Specific for AutoPi - get when a device last sent data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "autopi"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "device ethereum address",
                        "name": "ethAddr",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "invalid eth addr"
                    },
                    "404": {
                        "description": "no device found with eth addr or no data found"
                    },
                    "500": {
                        "description": "no device found or no data found, or other transient error"
                    }
                }
            }
        },
        "/v1/user/device-data/{userDeviceID}/daily-distance": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get kilometers driven for a userDeviceID each day.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device-data"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "user device id",
                        "name": "userDeviceID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IANAS time zone id, e.g., America/Los_Angeles",
                        "name": "time_zone",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controllers.DailyDistanceResp"
                        }
                    },
                    "404": {
                        "description": "no device found for user with provided parameters"
                    }
                }
            }
        },
        "/v1/user/device-data/{userDeviceID}/distance-driven": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get kilometers driven for a userDeviceID since connected (ie. since we have data available)\nif it returns 0 for distanceDriven it means we have no odometer data.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device-data"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "user device id",
                        "name": "userDeviceID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "no device found for user with provided parameters"
                    }
                }
            }
        },
        "/v1/user/device-data/{userDeviceID}/export/json/email": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Enqueues a data export job for the specified device. A link to download\na large JSON file of signals will be emailed to the address on file for the\ncurrent user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device-data"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "2OQjmqUt9dguQbJt1WImuVfje3W",
                        "description": "Device id",
                        "name": "userDeviceID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/user/device-data/{userDeviceID}/historical": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all historical data for a userDeviceID, within start and end range",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device-data"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "userDeviceID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "startDate eg 2022-01-02. if empty two weeks back",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "endDate eg 2022-03-01. if empty today",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/user/device-data/{userDeviceID}/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the latest status update for the device. May return 404 if the\nuser does not have a device with the ID, or if no status updates have come. Note this endpoint also exists under nft_controllers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device-data"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "user device ID",
                        "name": "user_device_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_DIMO-Network_device-data-api_internal_response.DeviceSnapshot"
                        }
                    }
                }
            }
        },
        "/v1/vehicle/{tokenID}/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all historical data for a tokenID, within start and end range",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device-data"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "token id",
                        "name": "tokenID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "startDate eg 2022-01-02. if empty two weeks back",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "endDate eg 2022-03-01. if empty today",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/vehicle/{tokenId}/status": {
            "get": {
                "description": "Returns the latest status update for the vehicle with a given token id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device-data"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "token id",
                        "name": "tokenId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_DIMO-Network_device-data-api_internal_response.DeviceSnapshot"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/v2/vehicle/{tokenID}/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all historical data for a tokenID, within start and end range",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device-data"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "token id",
                        "name": "tokenID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "startDate eg 2022-01-02. if empty two weeks back",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "endDate eg 2022-03-01. if empty today",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_DIMO-Network_device-data-api_internal_response.DeviceSnapshot": {
            "type": "object",
            "properties": {
                "ambientTemp": {
                    "type": "number"
                },
                "batteryCapacity": {
                    "type": "integer"
                },
                "batteryVoltage": {
                    "type": "number"
                },
                "chargeLimit": {
                    "type": "number"
                },
                "charging": {
                    "type": "boolean"
                },
                "fuelPercentRemaining": {
                    "type": "number"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "odometer": {
                    "type": "number"
                },
                "oil": {
                    "type": "number"
                },
                "range": {
                    "type": "number"
                },
                "recordCreatedAt": {
                    "type": "string"
                },
                "recordUpdatedAt": {
                    "type": "string"
                },
                "soc": {
                    "type": "number"
                },
                "tirePressure": {
                    "$ref": "#/definitions/smartcar.TirePressure"
                }
            }
        },
        "internal_controllers.DailyDistanceDay": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "distance": {
                    "type": "number"
                }
            }
        },
        "internal_controllers.DailyDistanceResp": {
            "type": "object",
            "properties": {
                "days": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_controllers.DailyDistanceDay"
                    }
                }
            }
        },
        "smartcar.TirePressure": {
            "type": "object",
            "properties": {
                "age": {
                    "description": "Deprecated: Should use DataAge instead of Age",
                    "type": "string"
                },
                "backLeft": {
                    "type": "number"
                },
                "backRight": {
                    "type": "number"
                },
                "dataAge": {
                    "type": "string"
                },
                "frontLeft": {
                    "type": "number"
                },
                "frontRight": {
                    "type": "number"
                },
                "requestId": {
                    "type": "string"
                },
                "unitSystem": {
                    "$ref": "#/definitions/smartcar.UnitSystem"
                }
            }
        },
        "smartcar.UnitSystem": {
            "type": "string",
            "enum": [
                "metric",
                "imperial"
            ],
            "x-enum-varnames": [
                "Metric",
                "Imperial"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "DIMO Device Data API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
