basePath: /v1
info:
  contact: {}
  title: DIMO Device Data API
  version: "1.0"
paths:
  /user/device-data/{userDeviceID}/historical:
    get:
      description: Get all historical data for a userDeviceID, within start and end
        range
      parameters:
      - description: user id
        in: path
        name: userDeviceID
        required: true
        type: string
      - description: startDate eg 2022-01-02. if empty two weeks back
        in: query
        name: startDate
        type: string
      - description: endDate eg 2022-03-01. if empty today
        in: query
        name: endDate
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      security:
      - BearerAuth: []
      tags:
      - device-data
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
