basePath: /v1
info:
  contact: {}
  title: DIMO Device Data API
  version: "1.0"
paths:
  /user/device-data/:userDeviceID/export/json/email:
    get:
      description: returns user data as json
      produces:
      - application/json
      responses:
        "200":
          description: OK
      tags:
      - device-data
  /user/device-data/{userDeviceID}/daily-distance:
    get:
      description: Get kilometers driven for a userDeviceID each day.
      parameters:
      - description: user device id
        in: path
        name: userDeviceID
        required: true
        type: string
      - description: IANAS time zone id, e.g., America/Los_Angeles
        in: query
        name: time_zone
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: no device found for user with provided parameters
      security:
      - BearerAuth: []
      tags:
      - device-data
  /user/device-data/{userDeviceID}/distance-driven:
    get:
      description: |-
        Get kilometers driven for a userDeviceID since connected (ie. since we have data available)
        if it returns 0 for distanceDriven it means we have no odometer data.
      parameters:
      - description: user device id
        in: path
        name: userDeviceID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: no device found for user with provided parameters
      security:
      - BearerAuth: []
      tags:
      - device-data
  /user/device-data/{userDeviceID}/historical:
    get:
      description: Get all historical data for a userDeviceID, within start and end
        range
      parameters:
      - description: user id
        in: path
        name: userDeviceID
        required: true
        type: string
      - description: startDate eg 2022-01-02. if empty two weeks back
        in: query
        name: startDate
        type: string
      - description: endDate eg 2022-03-01. if empty today
        in: query
        name: endDate
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      tags:
      - device-data
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
