// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ReportVehicleSignalsEventsAll      string
	ReportVehicleSignalsEventsSummary  string
	ReportVehicleSignalsEventsTracking string
	UserDeviceData                     string
	VehicleSignalsAvailableProperties  string
	VehicleSignalsJob                  string
}{
	ReportVehicleSignalsEventsAll:      "report_vehicle_signals_events_all",
	ReportVehicleSignalsEventsSummary:  "report_vehicle_signals_events_summary",
	ReportVehicleSignalsEventsTracking: "report_vehicle_signals_events_tracking",
	UserDeviceData:                     "user_device_data",
	VehicleSignalsAvailableProperties:  "vehicle_signals_available_properties",
	VehicleSignalsJob:                  "vehicle_signals_job",
}
