// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	UserDeviceData                             string
	VehicleDataTrackingEventsMissingProperties string
	VehicleDataTrackingEventsProperties        string
	VehicleDataTrackingProperties              string
}{
	UserDeviceData: "user_device_data",
	VehicleDataTrackingEventsMissingProperties: "vehicle_data_tracking_events_missing_properties",
	VehicleDataTrackingEventsProperties:        "vehicle_data_tracking_events_properties",
	VehicleDataTrackingProperties:              "vehicle_data_tracking_properties",
}
