// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ReportVehicleSignalsEventsAll      string
	ReportVehicleSignalsEventsTracking string
	UserDeviceData                     string
	VehicleSignalsAvailableProperties  string
}{
	ReportVehicleSignalsEventsAll:      "report_vehicle_signals_events_all",
	ReportVehicleSignalsEventsTracking: "report_vehicle_signals_events_tracking",
	UserDeviceData:                     "user_device_data",
	VehicleSignalsAvailableProperties:  "vehicle_signals_available_properties",
}
