// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// ReportVehicleSignalsEventsProperty is an object representing the database table.
type ReportVehicleSignalsEventsProperty struct {
	DateID             string    `boil:"date_id" json:"date_id" toml:"date_id" yaml:"date_id"`
	IntegrationID      string    `boil:"integration_id" json:"integration_id" toml:"integration_id" yaml:"integration_id"`
	DeviceMakeID       string    `boil:"device_make_id" json:"device_make_id" toml:"device_make_id" yaml:"device_make_id"`
	PropertyID         string    `boil:"property_id" json:"property_id" toml:"property_id" yaml:"property_id"`
	Model              string    `boil:"model" json:"model" toml:"model" yaml:"model"`
	Year               int       `boil:"year" json:"year" toml:"year" yaml:"year"`
	DeviceDefinitionID string    `boil:"device_definition_id" json:"device_definition_id" toml:"device_definition_id" yaml:"device_definition_id"`
	DeviceMake         string    `boil:"device_make" json:"device_make" toml:"device_make" yaml:"device_make"`
	Count              int       `boil:"count" json:"count" toml:"count" yaml:"count"`
	CreatedAt          time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *reportVehicleSignalsEventsPropertyR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L reportVehicleSignalsEventsPropertyL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ReportVehicleSignalsEventsPropertyColumns = struct {
	DateID             string
	IntegrationID      string
	DeviceMakeID       string
	PropertyID         string
	Model              string
	Year               string
	DeviceDefinitionID string
	DeviceMake         string
	Count              string
	CreatedAt          string
}{
	DateID:             "date_id",
	IntegrationID:      "integration_id",
	DeviceMakeID:       "device_make_id",
	PropertyID:         "property_id",
	Model:              "model",
	Year:               "year",
	DeviceDefinitionID: "device_definition_id",
	DeviceMake:         "device_make",
	Count:              "count",
	CreatedAt:          "created_at",
}

var ReportVehicleSignalsEventsPropertyTableColumns = struct {
	DateID             string
	IntegrationID      string
	DeviceMakeID       string
	PropertyID         string
	Model              string
	Year               string
	DeviceDefinitionID string
	DeviceMake         string
	Count              string
	CreatedAt          string
}{
	DateID:             "report_vehicle_signals_events_properties.date_id",
	IntegrationID:      "report_vehicle_signals_events_properties.integration_id",
	DeviceMakeID:       "report_vehicle_signals_events_properties.device_make_id",
	PropertyID:         "report_vehicle_signals_events_properties.property_id",
	Model:              "report_vehicle_signals_events_properties.model",
	Year:               "report_vehicle_signals_events_properties.year",
	DeviceDefinitionID: "report_vehicle_signals_events_properties.device_definition_id",
	DeviceMake:         "report_vehicle_signals_events_properties.device_make",
	Count:              "report_vehicle_signals_events_properties.count",
	CreatedAt:          "report_vehicle_signals_events_properties.created_at",
}

// Generated where

var ReportVehicleSignalsEventsPropertyWhere = struct {
	DateID             whereHelperstring
	IntegrationID      whereHelperstring
	DeviceMakeID       whereHelperstring
	PropertyID         whereHelperstring
	Model              whereHelperstring
	Year               whereHelperint
	DeviceDefinitionID whereHelperstring
	DeviceMake         whereHelperstring
	Count              whereHelperint
	CreatedAt          whereHelpertime_Time
}{
	DateID:             whereHelperstring{field: "\"device_data_api\".\"report_vehicle_signals_events_properties\".\"date_id\""},
	IntegrationID:      whereHelperstring{field: "\"device_data_api\".\"report_vehicle_signals_events_properties\".\"integration_id\""},
	DeviceMakeID:       whereHelperstring{field: "\"device_data_api\".\"report_vehicle_signals_events_properties\".\"device_make_id\""},
	PropertyID:         whereHelperstring{field: "\"device_data_api\".\"report_vehicle_signals_events_properties\".\"property_id\""},
	Model:              whereHelperstring{field: "\"device_data_api\".\"report_vehicle_signals_events_properties\".\"model\""},
	Year:               whereHelperint{field: "\"device_data_api\".\"report_vehicle_signals_events_properties\".\"year\""},
	DeviceDefinitionID: whereHelperstring{field: "\"device_data_api\".\"report_vehicle_signals_events_properties\".\"device_definition_id\""},
	DeviceMake:         whereHelperstring{field: "\"device_data_api\".\"report_vehicle_signals_events_properties\".\"device_make\""},
	Count:              whereHelperint{field: "\"device_data_api\".\"report_vehicle_signals_events_properties\".\"count\""},
	CreatedAt:          whereHelpertime_Time{field: "\"device_data_api\".\"report_vehicle_signals_events_properties\".\"created_at\""},
}

// ReportVehicleSignalsEventsPropertyRels is where relationship names are stored.
var ReportVehicleSignalsEventsPropertyRels = struct {
}{}

// reportVehicleSignalsEventsPropertyR is where relationships are stored.
type reportVehicleSignalsEventsPropertyR struct {
}

// NewStruct creates a new relationship struct
func (*reportVehicleSignalsEventsPropertyR) NewStruct() *reportVehicleSignalsEventsPropertyR {
	return &reportVehicleSignalsEventsPropertyR{}
}

// reportVehicleSignalsEventsPropertyL is where Load methods for each relationship are stored.
type reportVehicleSignalsEventsPropertyL struct{}

var (
	reportVehicleSignalsEventsPropertyAllColumns            = []string{"date_id", "integration_id", "device_make_id", "property_id", "model", "year", "device_definition_id", "device_make", "count", "created_at"}
	reportVehicleSignalsEventsPropertyColumnsWithoutDefault = []string{"date_id", "integration_id", "device_make_id", "property_id", "model", "year", "device_definition_id", "device_make", "count"}
	reportVehicleSignalsEventsPropertyColumnsWithDefault    = []string{"created_at"}
	reportVehicleSignalsEventsPropertyPrimaryKeyColumns     = []string{"date_id", "integration_id", "device_make_id", "property_id", "model", "year"}
	reportVehicleSignalsEventsPropertyGeneratedColumns      = []string{}
)

type (
	// ReportVehicleSignalsEventsPropertySlice is an alias for a slice of pointers to ReportVehicleSignalsEventsProperty.
	// This should almost always be used instead of []ReportVehicleSignalsEventsProperty.
	ReportVehicleSignalsEventsPropertySlice []*ReportVehicleSignalsEventsProperty
	// ReportVehicleSignalsEventsPropertyHook is the signature for custom ReportVehicleSignalsEventsProperty hook methods
	ReportVehicleSignalsEventsPropertyHook func(context.Context, boil.ContextExecutor, *ReportVehicleSignalsEventsProperty) error

	reportVehicleSignalsEventsPropertyQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	reportVehicleSignalsEventsPropertyType                 = reflect.TypeOf(&ReportVehicleSignalsEventsProperty{})
	reportVehicleSignalsEventsPropertyMapping              = queries.MakeStructMapping(reportVehicleSignalsEventsPropertyType)
	reportVehicleSignalsEventsPropertyPrimaryKeyMapping, _ = queries.BindMapping(reportVehicleSignalsEventsPropertyType, reportVehicleSignalsEventsPropertyMapping, reportVehicleSignalsEventsPropertyPrimaryKeyColumns)
	reportVehicleSignalsEventsPropertyInsertCacheMut       sync.RWMutex
	reportVehicleSignalsEventsPropertyInsertCache          = make(map[string]insertCache)
	reportVehicleSignalsEventsPropertyUpdateCacheMut       sync.RWMutex
	reportVehicleSignalsEventsPropertyUpdateCache          = make(map[string]updateCache)
	reportVehicleSignalsEventsPropertyUpsertCacheMut       sync.RWMutex
	reportVehicleSignalsEventsPropertyUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var reportVehicleSignalsEventsPropertyAfterSelectHooks []ReportVehicleSignalsEventsPropertyHook

var reportVehicleSignalsEventsPropertyBeforeInsertHooks []ReportVehicleSignalsEventsPropertyHook
var reportVehicleSignalsEventsPropertyAfterInsertHooks []ReportVehicleSignalsEventsPropertyHook

var reportVehicleSignalsEventsPropertyBeforeUpdateHooks []ReportVehicleSignalsEventsPropertyHook
var reportVehicleSignalsEventsPropertyAfterUpdateHooks []ReportVehicleSignalsEventsPropertyHook

var reportVehicleSignalsEventsPropertyBeforeDeleteHooks []ReportVehicleSignalsEventsPropertyHook
var reportVehicleSignalsEventsPropertyAfterDeleteHooks []ReportVehicleSignalsEventsPropertyHook

var reportVehicleSignalsEventsPropertyBeforeUpsertHooks []ReportVehicleSignalsEventsPropertyHook
var reportVehicleSignalsEventsPropertyAfterUpsertHooks []ReportVehicleSignalsEventsPropertyHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ReportVehicleSignalsEventsProperty) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range reportVehicleSignalsEventsPropertyAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ReportVehicleSignalsEventsProperty) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range reportVehicleSignalsEventsPropertyBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ReportVehicleSignalsEventsProperty) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range reportVehicleSignalsEventsPropertyAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ReportVehicleSignalsEventsProperty) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range reportVehicleSignalsEventsPropertyBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ReportVehicleSignalsEventsProperty) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range reportVehicleSignalsEventsPropertyAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ReportVehicleSignalsEventsProperty) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range reportVehicleSignalsEventsPropertyBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ReportVehicleSignalsEventsProperty) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range reportVehicleSignalsEventsPropertyAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ReportVehicleSignalsEventsProperty) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range reportVehicleSignalsEventsPropertyBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ReportVehicleSignalsEventsProperty) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range reportVehicleSignalsEventsPropertyAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddReportVehicleSignalsEventsPropertyHook registers your hook function for all future operations.
func AddReportVehicleSignalsEventsPropertyHook(hookPoint boil.HookPoint, reportVehicleSignalsEventsPropertyHook ReportVehicleSignalsEventsPropertyHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		reportVehicleSignalsEventsPropertyAfterSelectHooks = append(reportVehicleSignalsEventsPropertyAfterSelectHooks, reportVehicleSignalsEventsPropertyHook)
	case boil.BeforeInsertHook:
		reportVehicleSignalsEventsPropertyBeforeInsertHooks = append(reportVehicleSignalsEventsPropertyBeforeInsertHooks, reportVehicleSignalsEventsPropertyHook)
	case boil.AfterInsertHook:
		reportVehicleSignalsEventsPropertyAfterInsertHooks = append(reportVehicleSignalsEventsPropertyAfterInsertHooks, reportVehicleSignalsEventsPropertyHook)
	case boil.BeforeUpdateHook:
		reportVehicleSignalsEventsPropertyBeforeUpdateHooks = append(reportVehicleSignalsEventsPropertyBeforeUpdateHooks, reportVehicleSignalsEventsPropertyHook)
	case boil.AfterUpdateHook:
		reportVehicleSignalsEventsPropertyAfterUpdateHooks = append(reportVehicleSignalsEventsPropertyAfterUpdateHooks, reportVehicleSignalsEventsPropertyHook)
	case boil.BeforeDeleteHook:
		reportVehicleSignalsEventsPropertyBeforeDeleteHooks = append(reportVehicleSignalsEventsPropertyBeforeDeleteHooks, reportVehicleSignalsEventsPropertyHook)
	case boil.AfterDeleteHook:
		reportVehicleSignalsEventsPropertyAfterDeleteHooks = append(reportVehicleSignalsEventsPropertyAfterDeleteHooks, reportVehicleSignalsEventsPropertyHook)
	case boil.BeforeUpsertHook:
		reportVehicleSignalsEventsPropertyBeforeUpsertHooks = append(reportVehicleSignalsEventsPropertyBeforeUpsertHooks, reportVehicleSignalsEventsPropertyHook)
	case boil.AfterUpsertHook:
		reportVehicleSignalsEventsPropertyAfterUpsertHooks = append(reportVehicleSignalsEventsPropertyAfterUpsertHooks, reportVehicleSignalsEventsPropertyHook)
	}
}

// One returns a single reportVehicleSignalsEventsProperty record from the query.
func (q reportVehicleSignalsEventsPropertyQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ReportVehicleSignalsEventsProperty, error) {
	o := &ReportVehicleSignalsEventsProperty{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for report_vehicle_signals_events_properties")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ReportVehicleSignalsEventsProperty records from the query.
func (q reportVehicleSignalsEventsPropertyQuery) All(ctx context.Context, exec boil.ContextExecutor) (ReportVehicleSignalsEventsPropertySlice, error) {
	var o []*ReportVehicleSignalsEventsProperty

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ReportVehicleSignalsEventsProperty slice")
	}

	if len(reportVehicleSignalsEventsPropertyAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ReportVehicleSignalsEventsProperty records in the query.
func (q reportVehicleSignalsEventsPropertyQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count report_vehicle_signals_events_properties rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q reportVehicleSignalsEventsPropertyQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if report_vehicle_signals_events_properties exists")
	}

	return count > 0, nil
}

// ReportVehicleSignalsEventsProperties retrieves all the records using an executor.
func ReportVehicleSignalsEventsProperties(mods ...qm.QueryMod) reportVehicleSignalsEventsPropertyQuery {
	mods = append(mods, qm.From("\"device_data_api\".\"report_vehicle_signals_events_properties\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"device_data_api\".\"report_vehicle_signals_events_properties\".*"})
	}

	return reportVehicleSignalsEventsPropertyQuery{q}
}

// FindReportVehicleSignalsEventsProperty retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindReportVehicleSignalsEventsProperty(ctx context.Context, exec boil.ContextExecutor, dateID string, integrationID string, deviceMakeID string, propertyID string, model string, year int, selectCols ...string) (*ReportVehicleSignalsEventsProperty, error) {
	reportVehicleSignalsEventsPropertyObj := &ReportVehicleSignalsEventsProperty{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"device_data_api\".\"report_vehicle_signals_events_properties\" where \"date_id\"=$1 AND \"integration_id\"=$2 AND \"device_make_id\"=$3 AND \"property_id\"=$4 AND \"model\"=$5 AND \"year\"=$6", sel,
	)

	q := queries.Raw(query, dateID, integrationID, deviceMakeID, propertyID, model, year)

	err := q.Bind(ctx, exec, reportVehicleSignalsEventsPropertyObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from report_vehicle_signals_events_properties")
	}

	if err = reportVehicleSignalsEventsPropertyObj.doAfterSelectHooks(ctx, exec); err != nil {
		return reportVehicleSignalsEventsPropertyObj, err
	}

	return reportVehicleSignalsEventsPropertyObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ReportVehicleSignalsEventsProperty) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no report_vehicle_signals_events_properties provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(reportVehicleSignalsEventsPropertyColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	reportVehicleSignalsEventsPropertyInsertCacheMut.RLock()
	cache, cached := reportVehicleSignalsEventsPropertyInsertCache[key]
	reportVehicleSignalsEventsPropertyInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			reportVehicleSignalsEventsPropertyAllColumns,
			reportVehicleSignalsEventsPropertyColumnsWithDefault,
			reportVehicleSignalsEventsPropertyColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(reportVehicleSignalsEventsPropertyType, reportVehicleSignalsEventsPropertyMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(reportVehicleSignalsEventsPropertyType, reportVehicleSignalsEventsPropertyMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"device_data_api\".\"report_vehicle_signals_events_properties\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"device_data_api\".\"report_vehicle_signals_events_properties\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into report_vehicle_signals_events_properties")
	}

	if !cached {
		reportVehicleSignalsEventsPropertyInsertCacheMut.Lock()
		reportVehicleSignalsEventsPropertyInsertCache[key] = cache
		reportVehicleSignalsEventsPropertyInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ReportVehicleSignalsEventsProperty.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ReportVehicleSignalsEventsProperty) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	reportVehicleSignalsEventsPropertyUpdateCacheMut.RLock()
	cache, cached := reportVehicleSignalsEventsPropertyUpdateCache[key]
	reportVehicleSignalsEventsPropertyUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			reportVehicleSignalsEventsPropertyAllColumns,
			reportVehicleSignalsEventsPropertyPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update report_vehicle_signals_events_properties, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"device_data_api\".\"report_vehicle_signals_events_properties\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, reportVehicleSignalsEventsPropertyPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(reportVehicleSignalsEventsPropertyType, reportVehicleSignalsEventsPropertyMapping, append(wl, reportVehicleSignalsEventsPropertyPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update report_vehicle_signals_events_properties row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for report_vehicle_signals_events_properties")
	}

	if !cached {
		reportVehicleSignalsEventsPropertyUpdateCacheMut.Lock()
		reportVehicleSignalsEventsPropertyUpdateCache[key] = cache
		reportVehicleSignalsEventsPropertyUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q reportVehicleSignalsEventsPropertyQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for report_vehicle_signals_events_properties")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for report_vehicle_signals_events_properties")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ReportVehicleSignalsEventsPropertySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), reportVehicleSignalsEventsPropertyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"device_data_api\".\"report_vehicle_signals_events_properties\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, reportVehicleSignalsEventsPropertyPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in reportVehicleSignalsEventsProperty slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all reportVehicleSignalsEventsProperty")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ReportVehicleSignalsEventsProperty) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no report_vehicle_signals_events_properties provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(reportVehicleSignalsEventsPropertyColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	reportVehicleSignalsEventsPropertyUpsertCacheMut.RLock()
	cache, cached := reportVehicleSignalsEventsPropertyUpsertCache[key]
	reportVehicleSignalsEventsPropertyUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			reportVehicleSignalsEventsPropertyAllColumns,
			reportVehicleSignalsEventsPropertyColumnsWithDefault,
			reportVehicleSignalsEventsPropertyColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			reportVehicleSignalsEventsPropertyAllColumns,
			reportVehicleSignalsEventsPropertyPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert report_vehicle_signals_events_properties, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(reportVehicleSignalsEventsPropertyPrimaryKeyColumns))
			copy(conflict, reportVehicleSignalsEventsPropertyPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"device_data_api\".\"report_vehicle_signals_events_properties\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(reportVehicleSignalsEventsPropertyType, reportVehicleSignalsEventsPropertyMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(reportVehicleSignalsEventsPropertyType, reportVehicleSignalsEventsPropertyMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert report_vehicle_signals_events_properties")
	}

	if !cached {
		reportVehicleSignalsEventsPropertyUpsertCacheMut.Lock()
		reportVehicleSignalsEventsPropertyUpsertCache[key] = cache
		reportVehicleSignalsEventsPropertyUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ReportVehicleSignalsEventsProperty record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ReportVehicleSignalsEventsProperty) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ReportVehicleSignalsEventsProperty provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), reportVehicleSignalsEventsPropertyPrimaryKeyMapping)
	sql := "DELETE FROM \"device_data_api\".\"report_vehicle_signals_events_properties\" WHERE \"date_id\"=$1 AND \"integration_id\"=$2 AND \"device_make_id\"=$3 AND \"property_id\"=$4 AND \"model\"=$5 AND \"year\"=$6"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from report_vehicle_signals_events_properties")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for report_vehicle_signals_events_properties")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q reportVehicleSignalsEventsPropertyQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no reportVehicleSignalsEventsPropertyQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from report_vehicle_signals_events_properties")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for report_vehicle_signals_events_properties")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ReportVehicleSignalsEventsPropertySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(reportVehicleSignalsEventsPropertyBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), reportVehicleSignalsEventsPropertyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"device_data_api\".\"report_vehicle_signals_events_properties\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, reportVehicleSignalsEventsPropertyPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from reportVehicleSignalsEventsProperty slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for report_vehicle_signals_events_properties")
	}

	if len(reportVehicleSignalsEventsPropertyAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ReportVehicleSignalsEventsProperty) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindReportVehicleSignalsEventsProperty(ctx, exec, o.DateID, o.IntegrationID, o.DeviceMakeID, o.PropertyID, o.Model, o.Year)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ReportVehicleSignalsEventsPropertySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ReportVehicleSignalsEventsPropertySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), reportVehicleSignalsEventsPropertyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"device_data_api\".\"report_vehicle_signals_events_properties\".* FROM \"device_data_api\".\"report_vehicle_signals_events_properties\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, reportVehicleSignalsEventsPropertyPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ReportVehicleSignalsEventsPropertySlice")
	}

	*o = slice

	return nil
}

// ReportVehicleSignalsEventsPropertyExists checks if the ReportVehicleSignalsEventsProperty row exists.
func ReportVehicleSignalsEventsPropertyExists(ctx context.Context, exec boil.ContextExecutor, dateID string, integrationID string, deviceMakeID string, propertyID string, model string, year int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"device_data_api\".\"report_vehicle_signals_events_properties\" where \"date_id\"=$1 AND \"integration_id\"=$2 AND \"device_make_id\"=$3 AND \"property_id\"=$4 AND \"model\"=$5 AND \"year\"=$6 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, dateID, integrationID, deviceMakeID, propertyID, model, year)
	}
	row := exec.QueryRowContext(ctx, sql, dateID, integrationID, deviceMakeID, propertyID, model, year)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if report_vehicle_signals_events_properties exists")
	}

	return exists, nil
}

// Exists checks if the ReportVehicleSignalsEventsProperty row exists.
func (o *ReportVehicleSignalsEventsProperty) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ReportVehicleSignalsEventsPropertyExists(ctx, exec, o.DateID, o.IntegrationID, o.DeviceMakeID, o.PropertyID, o.Model, o.Year)
}
