// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// ReportVehicleSignalsEvent is an object representing the database table.
type ReportVehicleSignalsEvent struct {
	DateID             string    `boil:"date_id" json:"date_id" toml:"date_id" yaml:"date_id"`
	IntegrationID      string    `boil:"integration_id" json:"integration_id" toml:"integration_id" yaml:"integration_id"`
	DeviceMakeID       string    `boil:"device_make_id" json:"device_make_id" toml:"device_make_id" yaml:"device_make_id"`
	PropertyID         string    `boil:"property_id" json:"property_id" toml:"property_id" yaml:"property_id"`
	Model              string    `boil:"model" json:"model" toml:"model" yaml:"model"`
	Year               int       `boil:"year" json:"year" toml:"year" yaml:"year"`
	DeviceDefinitionID string    `boil:"device_definition_id" json:"device_definition_id" toml:"device_definition_id" yaml:"device_definition_id"`
	DeviceMake         string    `boil:"device_make" json:"device_make" toml:"device_make" yaml:"device_make"`
	Count              int       `boil:"count" json:"count" toml:"count" yaml:"count"`
	CreatedAt          time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *reportVehicleSignalsEventR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L reportVehicleSignalsEventL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ReportVehicleSignalsEventColumns = struct {
	DateID             string
	IntegrationID      string
	DeviceMakeID       string
	PropertyID         string
	Model              string
	Year               string
	DeviceDefinitionID string
	DeviceMake         string
	Count              string
	CreatedAt          string
}{
	DateID:             "date_id",
	IntegrationID:      "integration_id",
	DeviceMakeID:       "device_make_id",
	PropertyID:         "property_id",
	Model:              "model",
	Year:               "year",
	DeviceDefinitionID: "device_definition_id",
	DeviceMake:         "device_make",
	Count:              "count",
	CreatedAt:          "created_at",
}

var ReportVehicleSignalsEventTableColumns = struct {
	DateID             string
	IntegrationID      string
	DeviceMakeID       string
	PropertyID         string
	Model              string
	Year               string
	DeviceDefinitionID string
	DeviceMake         string
	Count              string
	CreatedAt          string
}{
	DateID:             "report_vehicle_signals_events.date_id",
	IntegrationID:      "report_vehicle_signals_events.integration_id",
	DeviceMakeID:       "report_vehicle_signals_events.device_make_id",
	PropertyID:         "report_vehicle_signals_events.property_id",
	Model:              "report_vehicle_signals_events.model",
	Year:               "report_vehicle_signals_events.year",
	DeviceDefinitionID: "report_vehicle_signals_events.device_definition_id",
	DeviceMake:         "report_vehicle_signals_events.device_make",
	Count:              "report_vehicle_signals_events.count",
	CreatedAt:          "report_vehicle_signals_events.created_at",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var ReportVehicleSignalsEventWhere = struct {
	DateID             whereHelperstring
	IntegrationID      whereHelperstring
	DeviceMakeID       whereHelperstring
	PropertyID         whereHelperstring
	Model              whereHelperstring
	Year               whereHelperint
	DeviceDefinitionID whereHelperstring
	DeviceMake         whereHelperstring
	Count              whereHelperint
	CreatedAt          whereHelpertime_Time
}{
	DateID:             whereHelperstring{field: "\"device_data_api\".\"report_vehicle_signals_events\".\"date_id\""},
	IntegrationID:      whereHelperstring{field: "\"device_data_api\".\"report_vehicle_signals_events\".\"integration_id\""},
	DeviceMakeID:       whereHelperstring{field: "\"device_data_api\".\"report_vehicle_signals_events\".\"device_make_id\""},
	PropertyID:         whereHelperstring{field: "\"device_data_api\".\"report_vehicle_signals_events\".\"property_id\""},
	Model:              whereHelperstring{field: "\"device_data_api\".\"report_vehicle_signals_events\".\"model\""},
	Year:               whereHelperint{field: "\"device_data_api\".\"report_vehicle_signals_events\".\"year\""},
	DeviceDefinitionID: whereHelperstring{field: "\"device_data_api\".\"report_vehicle_signals_events\".\"device_definition_id\""},
	DeviceMake:         whereHelperstring{field: "\"device_data_api\".\"report_vehicle_signals_events\".\"device_make\""},
	Count:              whereHelperint{field: "\"device_data_api\".\"report_vehicle_signals_events\".\"count\""},
	CreatedAt:          whereHelpertime_Time{field: "\"device_data_api\".\"report_vehicle_signals_events\".\"created_at\""},
}

// ReportVehicleSignalsEventRels is where relationship names are stored.
var ReportVehicleSignalsEventRels = struct {
}{}

// reportVehicleSignalsEventR is where relationships are stored.
type reportVehicleSignalsEventR struct {
}

// NewStruct creates a new relationship struct
func (*reportVehicleSignalsEventR) NewStruct() *reportVehicleSignalsEventR {
	return &reportVehicleSignalsEventR{}
}

// reportVehicleSignalsEventL is where Load methods for each relationship are stored.
type reportVehicleSignalsEventL struct{}

var (
	reportVehicleSignalsEventAllColumns            = []string{"date_id", "integration_id", "device_make_id", "property_id", "model", "year", "device_definition_id", "device_make", "count", "created_at"}
	reportVehicleSignalsEventColumnsWithoutDefault = []string{"date_id", "integration_id", "device_make_id", "property_id", "model", "year", "device_definition_id", "device_make", "count"}
	reportVehicleSignalsEventColumnsWithDefault    = []string{"created_at"}
	reportVehicleSignalsEventPrimaryKeyColumns     = []string{"date_id", "integration_id", "device_make_id", "property_id", "model", "year"}
	reportVehicleSignalsEventGeneratedColumns      = []string{}
)

type (
	// ReportVehicleSignalsEventSlice is an alias for a slice of pointers to ReportVehicleSignalsEvent.
	// This should almost always be used instead of []ReportVehicleSignalsEvent.
	ReportVehicleSignalsEventSlice []*ReportVehicleSignalsEvent
	// ReportVehicleSignalsEventHook is the signature for custom ReportVehicleSignalsEvent hook methods
	ReportVehicleSignalsEventHook func(context.Context, boil.ContextExecutor, *ReportVehicleSignalsEvent) error

	reportVehicleSignalsEventQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	reportVehicleSignalsEventType                 = reflect.TypeOf(&ReportVehicleSignalsEvent{})
	reportVehicleSignalsEventMapping              = queries.MakeStructMapping(reportVehicleSignalsEventType)
	reportVehicleSignalsEventPrimaryKeyMapping, _ = queries.BindMapping(reportVehicleSignalsEventType, reportVehicleSignalsEventMapping, reportVehicleSignalsEventPrimaryKeyColumns)
	reportVehicleSignalsEventInsertCacheMut       sync.RWMutex
	reportVehicleSignalsEventInsertCache          = make(map[string]insertCache)
	reportVehicleSignalsEventUpdateCacheMut       sync.RWMutex
	reportVehicleSignalsEventUpdateCache          = make(map[string]updateCache)
	reportVehicleSignalsEventUpsertCacheMut       sync.RWMutex
	reportVehicleSignalsEventUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var reportVehicleSignalsEventAfterSelectHooks []ReportVehicleSignalsEventHook

var reportVehicleSignalsEventBeforeInsertHooks []ReportVehicleSignalsEventHook
var reportVehicleSignalsEventAfterInsertHooks []ReportVehicleSignalsEventHook

var reportVehicleSignalsEventBeforeUpdateHooks []ReportVehicleSignalsEventHook
var reportVehicleSignalsEventAfterUpdateHooks []ReportVehicleSignalsEventHook

var reportVehicleSignalsEventBeforeDeleteHooks []ReportVehicleSignalsEventHook
var reportVehicleSignalsEventAfterDeleteHooks []ReportVehicleSignalsEventHook

var reportVehicleSignalsEventBeforeUpsertHooks []ReportVehicleSignalsEventHook
var reportVehicleSignalsEventAfterUpsertHooks []ReportVehicleSignalsEventHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ReportVehicleSignalsEvent) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range reportVehicleSignalsEventAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ReportVehicleSignalsEvent) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range reportVehicleSignalsEventBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ReportVehicleSignalsEvent) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range reportVehicleSignalsEventAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ReportVehicleSignalsEvent) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range reportVehicleSignalsEventBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ReportVehicleSignalsEvent) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range reportVehicleSignalsEventAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ReportVehicleSignalsEvent) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range reportVehicleSignalsEventBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ReportVehicleSignalsEvent) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range reportVehicleSignalsEventAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ReportVehicleSignalsEvent) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range reportVehicleSignalsEventBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ReportVehicleSignalsEvent) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range reportVehicleSignalsEventAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddReportVehicleSignalsEventHook registers your hook function for all future operations.
func AddReportVehicleSignalsEventHook(hookPoint boil.HookPoint, reportVehicleSignalsEventHook ReportVehicleSignalsEventHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		reportVehicleSignalsEventAfterSelectHooks = append(reportVehicleSignalsEventAfterSelectHooks, reportVehicleSignalsEventHook)
	case boil.BeforeInsertHook:
		reportVehicleSignalsEventBeforeInsertHooks = append(reportVehicleSignalsEventBeforeInsertHooks, reportVehicleSignalsEventHook)
	case boil.AfterInsertHook:
		reportVehicleSignalsEventAfterInsertHooks = append(reportVehicleSignalsEventAfterInsertHooks, reportVehicleSignalsEventHook)
	case boil.BeforeUpdateHook:
		reportVehicleSignalsEventBeforeUpdateHooks = append(reportVehicleSignalsEventBeforeUpdateHooks, reportVehicleSignalsEventHook)
	case boil.AfterUpdateHook:
		reportVehicleSignalsEventAfterUpdateHooks = append(reportVehicleSignalsEventAfterUpdateHooks, reportVehicleSignalsEventHook)
	case boil.BeforeDeleteHook:
		reportVehicleSignalsEventBeforeDeleteHooks = append(reportVehicleSignalsEventBeforeDeleteHooks, reportVehicleSignalsEventHook)
	case boil.AfterDeleteHook:
		reportVehicleSignalsEventAfterDeleteHooks = append(reportVehicleSignalsEventAfterDeleteHooks, reportVehicleSignalsEventHook)
	case boil.BeforeUpsertHook:
		reportVehicleSignalsEventBeforeUpsertHooks = append(reportVehicleSignalsEventBeforeUpsertHooks, reportVehicleSignalsEventHook)
	case boil.AfterUpsertHook:
		reportVehicleSignalsEventAfterUpsertHooks = append(reportVehicleSignalsEventAfterUpsertHooks, reportVehicleSignalsEventHook)
	}
}

// One returns a single reportVehicleSignalsEvent record from the query.
func (q reportVehicleSignalsEventQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ReportVehicleSignalsEvent, error) {
	o := &ReportVehicleSignalsEvent{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for report_vehicle_signals_events")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ReportVehicleSignalsEvent records from the query.
func (q reportVehicleSignalsEventQuery) All(ctx context.Context, exec boil.ContextExecutor) (ReportVehicleSignalsEventSlice, error) {
	var o []*ReportVehicleSignalsEvent

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ReportVehicleSignalsEvent slice")
	}

	if len(reportVehicleSignalsEventAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ReportVehicleSignalsEvent records in the query.
func (q reportVehicleSignalsEventQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count report_vehicle_signals_events rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q reportVehicleSignalsEventQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if report_vehicle_signals_events exists")
	}

	return count > 0, nil
}

// ReportVehicleSignalsEvents retrieves all the records using an executor.
func ReportVehicleSignalsEvents(mods ...qm.QueryMod) reportVehicleSignalsEventQuery {
	mods = append(mods, qm.From("\"device_data_api\".\"report_vehicle_signals_events\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"device_data_api\".\"report_vehicle_signals_events\".*"})
	}

	return reportVehicleSignalsEventQuery{q}
}

// FindReportVehicleSignalsEvent retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindReportVehicleSignalsEvent(ctx context.Context, exec boil.ContextExecutor, dateID string, integrationID string, deviceMakeID string, propertyID string, model string, year int, selectCols ...string) (*ReportVehicleSignalsEvent, error) {
	reportVehicleSignalsEventObj := &ReportVehicleSignalsEvent{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"device_data_api\".\"report_vehicle_signals_events\" where \"date_id\"=$1 AND \"integration_id\"=$2 AND \"device_make_id\"=$3 AND \"property_id\"=$4 AND \"model\"=$5 AND \"year\"=$6", sel,
	)

	q := queries.Raw(query, dateID, integrationID, deviceMakeID, propertyID, model, year)

	err := q.Bind(ctx, exec, reportVehicleSignalsEventObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from report_vehicle_signals_events")
	}

	if err = reportVehicleSignalsEventObj.doAfterSelectHooks(ctx, exec); err != nil {
		return reportVehicleSignalsEventObj, err
	}

	return reportVehicleSignalsEventObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ReportVehicleSignalsEvent) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no report_vehicle_signals_events provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(reportVehicleSignalsEventColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	reportVehicleSignalsEventInsertCacheMut.RLock()
	cache, cached := reportVehicleSignalsEventInsertCache[key]
	reportVehicleSignalsEventInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			reportVehicleSignalsEventAllColumns,
			reportVehicleSignalsEventColumnsWithDefault,
			reportVehicleSignalsEventColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(reportVehicleSignalsEventType, reportVehicleSignalsEventMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(reportVehicleSignalsEventType, reportVehicleSignalsEventMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"device_data_api\".\"report_vehicle_signals_events\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"device_data_api\".\"report_vehicle_signals_events\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into report_vehicle_signals_events")
	}

	if !cached {
		reportVehicleSignalsEventInsertCacheMut.Lock()
		reportVehicleSignalsEventInsertCache[key] = cache
		reportVehicleSignalsEventInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ReportVehicleSignalsEvent.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ReportVehicleSignalsEvent) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	reportVehicleSignalsEventUpdateCacheMut.RLock()
	cache, cached := reportVehicleSignalsEventUpdateCache[key]
	reportVehicleSignalsEventUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			reportVehicleSignalsEventAllColumns,
			reportVehicleSignalsEventPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update report_vehicle_signals_events, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"device_data_api\".\"report_vehicle_signals_events\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, reportVehicleSignalsEventPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(reportVehicleSignalsEventType, reportVehicleSignalsEventMapping, append(wl, reportVehicleSignalsEventPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update report_vehicle_signals_events row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for report_vehicle_signals_events")
	}

	if !cached {
		reportVehicleSignalsEventUpdateCacheMut.Lock()
		reportVehicleSignalsEventUpdateCache[key] = cache
		reportVehicleSignalsEventUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q reportVehicleSignalsEventQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for report_vehicle_signals_events")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for report_vehicle_signals_events")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ReportVehicleSignalsEventSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), reportVehicleSignalsEventPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"device_data_api\".\"report_vehicle_signals_events\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, reportVehicleSignalsEventPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in reportVehicleSignalsEvent slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all reportVehicleSignalsEvent")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ReportVehicleSignalsEvent) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no report_vehicle_signals_events provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(reportVehicleSignalsEventColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	reportVehicleSignalsEventUpsertCacheMut.RLock()
	cache, cached := reportVehicleSignalsEventUpsertCache[key]
	reportVehicleSignalsEventUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			reportVehicleSignalsEventAllColumns,
			reportVehicleSignalsEventColumnsWithDefault,
			reportVehicleSignalsEventColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			reportVehicleSignalsEventAllColumns,
			reportVehicleSignalsEventPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert report_vehicle_signals_events, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(reportVehicleSignalsEventPrimaryKeyColumns))
			copy(conflict, reportVehicleSignalsEventPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"device_data_api\".\"report_vehicle_signals_events\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(reportVehicleSignalsEventType, reportVehicleSignalsEventMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(reportVehicleSignalsEventType, reportVehicleSignalsEventMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert report_vehicle_signals_events")
	}

	if !cached {
		reportVehicleSignalsEventUpsertCacheMut.Lock()
		reportVehicleSignalsEventUpsertCache[key] = cache
		reportVehicleSignalsEventUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ReportVehicleSignalsEvent record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ReportVehicleSignalsEvent) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ReportVehicleSignalsEvent provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), reportVehicleSignalsEventPrimaryKeyMapping)
	sql := "DELETE FROM \"device_data_api\".\"report_vehicle_signals_events\" WHERE \"date_id\"=$1 AND \"integration_id\"=$2 AND \"device_make_id\"=$3 AND \"property_id\"=$4 AND \"model\"=$5 AND \"year\"=$6"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from report_vehicle_signals_events")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for report_vehicle_signals_events")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q reportVehicleSignalsEventQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no reportVehicleSignalsEventQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from report_vehicle_signals_events")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for report_vehicle_signals_events")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ReportVehicleSignalsEventSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(reportVehicleSignalsEventBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), reportVehicleSignalsEventPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"device_data_api\".\"report_vehicle_signals_events\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, reportVehicleSignalsEventPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from reportVehicleSignalsEvent slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for report_vehicle_signals_events")
	}

	if len(reportVehicleSignalsEventAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ReportVehicleSignalsEvent) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindReportVehicleSignalsEvent(ctx, exec, o.DateID, o.IntegrationID, o.DeviceMakeID, o.PropertyID, o.Model, o.Year)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ReportVehicleSignalsEventSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ReportVehicleSignalsEventSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), reportVehicleSignalsEventPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"device_data_api\".\"report_vehicle_signals_events\".* FROM \"device_data_api\".\"report_vehicle_signals_events\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, reportVehicleSignalsEventPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ReportVehicleSignalsEventSlice")
	}

	*o = slice

	return nil
}

// ReportVehicleSignalsEventExists checks if the ReportVehicleSignalsEvent row exists.
func ReportVehicleSignalsEventExists(ctx context.Context, exec boil.ContextExecutor, dateID string, integrationID string, deviceMakeID string, propertyID string, model string, year int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"device_data_api\".\"report_vehicle_signals_events\" where \"date_id\"=$1 AND \"integration_id\"=$2 AND \"device_make_id\"=$3 AND \"property_id\"=$4 AND \"model\"=$5 AND \"year\"=$6 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, dateID, integrationID, deviceMakeID, propertyID, model, year)
	}
	row := exec.QueryRowContext(ctx, sql, dateID, integrationID, deviceMakeID, propertyID, model, year)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if report_vehicle_signals_events exists")
	}

	return exists, nil
}
