// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// VehicleSignalsTrackingEventsProperty is an object representing the database table.
type VehicleSignalsTrackingEventsProperty struct {
	IntegrationID string      `boil:"integration_id" json:"integration_id" toml:"integration_id" yaml:"integration_id"`
	DeviceMakeID  string      `boil:"device_make_id" json:"device_make_id" toml:"device_make_id" yaml:"device_make_id"`
	PropertyID    string      `boil:"property_id" json:"property_id" toml:"property_id" yaml:"property_id"`
	Model         string      `boil:"model" json:"model" toml:"model" yaml:"model"`
	Year          int         `boil:"year" json:"year" toml:"year" yaml:"year"`
	Description   null.String `boil:"description" json:"description,omitempty" toml:"description" yaml:"description,omitempty"`
	Count         int         `boil:"count" json:"count" toml:"count" yaml:"count"`
	CreatedAt     time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *vehicleSignalsTrackingEventsPropertyR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L vehicleSignalsTrackingEventsPropertyL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var VehicleSignalsTrackingEventsPropertyColumns = struct {
	IntegrationID string
	DeviceMakeID  string
	PropertyID    string
	Model         string
	Year          string
	Description   string
	Count         string
	CreatedAt     string
}{
	IntegrationID: "integration_id",
	DeviceMakeID:  "device_make_id",
	PropertyID:    "property_id",
	Model:         "model",
	Year:          "year",
	Description:   "description",
	Count:         "count",
	CreatedAt:     "created_at",
}

var VehicleSignalsTrackingEventsPropertyTableColumns = struct {
	IntegrationID string
	DeviceMakeID  string
	PropertyID    string
	Model         string
	Year          string
	Description   string
	Count         string
	CreatedAt     string
}{
	IntegrationID: "vehicle_signals_tracking_events_properties.integration_id",
	DeviceMakeID:  "vehicle_signals_tracking_events_properties.device_make_id",
	PropertyID:    "vehicle_signals_tracking_events_properties.property_id",
	Model:         "vehicle_signals_tracking_events_properties.model",
	Year:          "vehicle_signals_tracking_events_properties.year",
	Description:   "vehicle_signals_tracking_events_properties.description",
	Count:         "vehicle_signals_tracking_events_properties.count",
	CreatedAt:     "vehicle_signals_tracking_events_properties.created_at",
}

// Generated where

var VehicleSignalsTrackingEventsPropertyWhere = struct {
	IntegrationID whereHelperstring
	DeviceMakeID  whereHelperstring
	PropertyID    whereHelperstring
	Model         whereHelperstring
	Year          whereHelperint
	Description   whereHelpernull_String
	Count         whereHelperint
	CreatedAt     whereHelpertime_Time
}{
	IntegrationID: whereHelperstring{field: "\"device_data_api\".\"vehicle_signals_tracking_events_properties\".\"integration_id\""},
	DeviceMakeID:  whereHelperstring{field: "\"device_data_api\".\"vehicle_signals_tracking_events_properties\".\"device_make_id\""},
	PropertyID:    whereHelperstring{field: "\"device_data_api\".\"vehicle_signals_tracking_events_properties\".\"property_id\""},
	Model:         whereHelperstring{field: "\"device_data_api\".\"vehicle_signals_tracking_events_properties\".\"model\""},
	Year:          whereHelperint{field: "\"device_data_api\".\"vehicle_signals_tracking_events_properties\".\"year\""},
	Description:   whereHelpernull_String{field: "\"device_data_api\".\"vehicle_signals_tracking_events_properties\".\"description\""},
	Count:         whereHelperint{field: "\"device_data_api\".\"vehicle_signals_tracking_events_properties\".\"count\""},
	CreatedAt:     whereHelpertime_Time{field: "\"device_data_api\".\"vehicle_signals_tracking_events_properties\".\"created_at\""},
}

// VehicleSignalsTrackingEventsPropertyRels is where relationship names are stored.
var VehicleSignalsTrackingEventsPropertyRels = struct {
}{}

// vehicleSignalsTrackingEventsPropertyR is where relationships are stored.
type vehicleSignalsTrackingEventsPropertyR struct {
}

// NewStruct creates a new relationship struct
func (*vehicleSignalsTrackingEventsPropertyR) NewStruct() *vehicleSignalsTrackingEventsPropertyR {
	return &vehicleSignalsTrackingEventsPropertyR{}
}

// vehicleSignalsTrackingEventsPropertyL is where Load methods for each relationship are stored.
type vehicleSignalsTrackingEventsPropertyL struct{}

var (
	vehicleSignalsTrackingEventsPropertyAllColumns            = []string{"integration_id", "device_make_id", "property_id", "model", "year", "description", "count", "created_at"}
	vehicleSignalsTrackingEventsPropertyColumnsWithoutDefault = []string{"integration_id", "device_make_id", "property_id", "model", "year", "count"}
	vehicleSignalsTrackingEventsPropertyColumnsWithDefault    = []string{"description", "created_at"}
	vehicleSignalsTrackingEventsPropertyPrimaryKeyColumns     = []string{"integration_id", "device_make_id", "property_id"}
	vehicleSignalsTrackingEventsPropertyGeneratedColumns      = []string{}
)

type (
	// VehicleSignalsTrackingEventsPropertySlice is an alias for a slice of pointers to VehicleSignalsTrackingEventsProperty.
	// This should almost always be used instead of []VehicleSignalsTrackingEventsProperty.
	VehicleSignalsTrackingEventsPropertySlice []*VehicleSignalsTrackingEventsProperty
	// VehicleSignalsTrackingEventsPropertyHook is the signature for custom VehicleSignalsTrackingEventsProperty hook methods
	VehicleSignalsTrackingEventsPropertyHook func(context.Context, boil.ContextExecutor, *VehicleSignalsTrackingEventsProperty) error

	vehicleSignalsTrackingEventsPropertyQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	vehicleSignalsTrackingEventsPropertyType                 = reflect.TypeOf(&VehicleSignalsTrackingEventsProperty{})
	vehicleSignalsTrackingEventsPropertyMapping              = queries.MakeStructMapping(vehicleSignalsTrackingEventsPropertyType)
	vehicleSignalsTrackingEventsPropertyPrimaryKeyMapping, _ = queries.BindMapping(vehicleSignalsTrackingEventsPropertyType, vehicleSignalsTrackingEventsPropertyMapping, vehicleSignalsTrackingEventsPropertyPrimaryKeyColumns)
	vehicleSignalsTrackingEventsPropertyInsertCacheMut       sync.RWMutex
	vehicleSignalsTrackingEventsPropertyInsertCache          = make(map[string]insertCache)
	vehicleSignalsTrackingEventsPropertyUpdateCacheMut       sync.RWMutex
	vehicleSignalsTrackingEventsPropertyUpdateCache          = make(map[string]updateCache)
	vehicleSignalsTrackingEventsPropertyUpsertCacheMut       sync.RWMutex
	vehicleSignalsTrackingEventsPropertyUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var vehicleSignalsTrackingEventsPropertyAfterSelectHooks []VehicleSignalsTrackingEventsPropertyHook

var vehicleSignalsTrackingEventsPropertyBeforeInsertHooks []VehicleSignalsTrackingEventsPropertyHook
var vehicleSignalsTrackingEventsPropertyAfterInsertHooks []VehicleSignalsTrackingEventsPropertyHook

var vehicleSignalsTrackingEventsPropertyBeforeUpdateHooks []VehicleSignalsTrackingEventsPropertyHook
var vehicleSignalsTrackingEventsPropertyAfterUpdateHooks []VehicleSignalsTrackingEventsPropertyHook

var vehicleSignalsTrackingEventsPropertyBeforeDeleteHooks []VehicleSignalsTrackingEventsPropertyHook
var vehicleSignalsTrackingEventsPropertyAfterDeleteHooks []VehicleSignalsTrackingEventsPropertyHook

var vehicleSignalsTrackingEventsPropertyBeforeUpsertHooks []VehicleSignalsTrackingEventsPropertyHook
var vehicleSignalsTrackingEventsPropertyAfterUpsertHooks []VehicleSignalsTrackingEventsPropertyHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *VehicleSignalsTrackingEventsProperty) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleSignalsTrackingEventsPropertyAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *VehicleSignalsTrackingEventsProperty) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleSignalsTrackingEventsPropertyBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *VehicleSignalsTrackingEventsProperty) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleSignalsTrackingEventsPropertyAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *VehicleSignalsTrackingEventsProperty) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleSignalsTrackingEventsPropertyBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *VehicleSignalsTrackingEventsProperty) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleSignalsTrackingEventsPropertyAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *VehicleSignalsTrackingEventsProperty) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleSignalsTrackingEventsPropertyBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *VehicleSignalsTrackingEventsProperty) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleSignalsTrackingEventsPropertyAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *VehicleSignalsTrackingEventsProperty) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleSignalsTrackingEventsPropertyBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *VehicleSignalsTrackingEventsProperty) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleSignalsTrackingEventsPropertyAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddVehicleSignalsTrackingEventsPropertyHook registers your hook function for all future operations.
func AddVehicleSignalsTrackingEventsPropertyHook(hookPoint boil.HookPoint, vehicleSignalsTrackingEventsPropertyHook VehicleSignalsTrackingEventsPropertyHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		vehicleSignalsTrackingEventsPropertyAfterSelectHooks = append(vehicleSignalsTrackingEventsPropertyAfterSelectHooks, vehicleSignalsTrackingEventsPropertyHook)
	case boil.BeforeInsertHook:
		vehicleSignalsTrackingEventsPropertyBeforeInsertHooks = append(vehicleSignalsTrackingEventsPropertyBeforeInsertHooks, vehicleSignalsTrackingEventsPropertyHook)
	case boil.AfterInsertHook:
		vehicleSignalsTrackingEventsPropertyAfterInsertHooks = append(vehicleSignalsTrackingEventsPropertyAfterInsertHooks, vehicleSignalsTrackingEventsPropertyHook)
	case boil.BeforeUpdateHook:
		vehicleSignalsTrackingEventsPropertyBeforeUpdateHooks = append(vehicleSignalsTrackingEventsPropertyBeforeUpdateHooks, vehicleSignalsTrackingEventsPropertyHook)
	case boil.AfterUpdateHook:
		vehicleSignalsTrackingEventsPropertyAfterUpdateHooks = append(vehicleSignalsTrackingEventsPropertyAfterUpdateHooks, vehicleSignalsTrackingEventsPropertyHook)
	case boil.BeforeDeleteHook:
		vehicleSignalsTrackingEventsPropertyBeforeDeleteHooks = append(vehicleSignalsTrackingEventsPropertyBeforeDeleteHooks, vehicleSignalsTrackingEventsPropertyHook)
	case boil.AfterDeleteHook:
		vehicleSignalsTrackingEventsPropertyAfterDeleteHooks = append(vehicleSignalsTrackingEventsPropertyAfterDeleteHooks, vehicleSignalsTrackingEventsPropertyHook)
	case boil.BeforeUpsertHook:
		vehicleSignalsTrackingEventsPropertyBeforeUpsertHooks = append(vehicleSignalsTrackingEventsPropertyBeforeUpsertHooks, vehicleSignalsTrackingEventsPropertyHook)
	case boil.AfterUpsertHook:
		vehicleSignalsTrackingEventsPropertyAfterUpsertHooks = append(vehicleSignalsTrackingEventsPropertyAfterUpsertHooks, vehicleSignalsTrackingEventsPropertyHook)
	}
}

// One returns a single vehicleSignalsTrackingEventsProperty record from the query.
func (q vehicleSignalsTrackingEventsPropertyQuery) One(ctx context.Context, exec boil.ContextExecutor) (*VehicleSignalsTrackingEventsProperty, error) {
	o := &VehicleSignalsTrackingEventsProperty{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for vehicle_signals_tracking_events_properties")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all VehicleSignalsTrackingEventsProperty records from the query.
func (q vehicleSignalsTrackingEventsPropertyQuery) All(ctx context.Context, exec boil.ContextExecutor) (VehicleSignalsTrackingEventsPropertySlice, error) {
	var o []*VehicleSignalsTrackingEventsProperty

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to VehicleSignalsTrackingEventsProperty slice")
	}

	if len(vehicleSignalsTrackingEventsPropertyAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all VehicleSignalsTrackingEventsProperty records in the query.
func (q vehicleSignalsTrackingEventsPropertyQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count vehicle_signals_tracking_events_properties rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q vehicleSignalsTrackingEventsPropertyQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if vehicle_signals_tracking_events_properties exists")
	}

	return count > 0, nil
}

// VehicleSignalsTrackingEventsProperties retrieves all the records using an executor.
func VehicleSignalsTrackingEventsProperties(mods ...qm.QueryMod) vehicleSignalsTrackingEventsPropertyQuery {
	mods = append(mods, qm.From("\"device_data_api\".\"vehicle_signals_tracking_events_properties\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"device_data_api\".\"vehicle_signals_tracking_events_properties\".*"})
	}

	return vehicleSignalsTrackingEventsPropertyQuery{q}
}

// FindVehicleSignalsTrackingEventsProperty retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindVehicleSignalsTrackingEventsProperty(ctx context.Context, exec boil.ContextExecutor, integrationID string, deviceMakeID string, propertyID string, selectCols ...string) (*VehicleSignalsTrackingEventsProperty, error) {
	vehicleSignalsTrackingEventsPropertyObj := &VehicleSignalsTrackingEventsProperty{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"device_data_api\".\"vehicle_signals_tracking_events_properties\" where \"integration_id\"=$1 AND \"device_make_id\"=$2 AND \"property_id\"=$3", sel,
	)

	q := queries.Raw(query, integrationID, deviceMakeID, propertyID)

	err := q.Bind(ctx, exec, vehicleSignalsTrackingEventsPropertyObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from vehicle_signals_tracking_events_properties")
	}

	if err = vehicleSignalsTrackingEventsPropertyObj.doAfterSelectHooks(ctx, exec); err != nil {
		return vehicleSignalsTrackingEventsPropertyObj, err
	}

	return vehicleSignalsTrackingEventsPropertyObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *VehicleSignalsTrackingEventsProperty) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no vehicle_signals_tracking_events_properties provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(vehicleSignalsTrackingEventsPropertyColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	vehicleSignalsTrackingEventsPropertyInsertCacheMut.RLock()
	cache, cached := vehicleSignalsTrackingEventsPropertyInsertCache[key]
	vehicleSignalsTrackingEventsPropertyInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			vehicleSignalsTrackingEventsPropertyAllColumns,
			vehicleSignalsTrackingEventsPropertyColumnsWithDefault,
			vehicleSignalsTrackingEventsPropertyColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(vehicleSignalsTrackingEventsPropertyType, vehicleSignalsTrackingEventsPropertyMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(vehicleSignalsTrackingEventsPropertyType, vehicleSignalsTrackingEventsPropertyMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"device_data_api\".\"vehicle_signals_tracking_events_properties\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"device_data_api\".\"vehicle_signals_tracking_events_properties\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into vehicle_signals_tracking_events_properties")
	}

	if !cached {
		vehicleSignalsTrackingEventsPropertyInsertCacheMut.Lock()
		vehicleSignalsTrackingEventsPropertyInsertCache[key] = cache
		vehicleSignalsTrackingEventsPropertyInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the VehicleSignalsTrackingEventsProperty.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *VehicleSignalsTrackingEventsProperty) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	vehicleSignalsTrackingEventsPropertyUpdateCacheMut.RLock()
	cache, cached := vehicleSignalsTrackingEventsPropertyUpdateCache[key]
	vehicleSignalsTrackingEventsPropertyUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			vehicleSignalsTrackingEventsPropertyAllColumns,
			vehicleSignalsTrackingEventsPropertyPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update vehicle_signals_tracking_events_properties, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"device_data_api\".\"vehicle_signals_tracking_events_properties\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, vehicleSignalsTrackingEventsPropertyPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(vehicleSignalsTrackingEventsPropertyType, vehicleSignalsTrackingEventsPropertyMapping, append(wl, vehicleSignalsTrackingEventsPropertyPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update vehicle_signals_tracking_events_properties row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for vehicle_signals_tracking_events_properties")
	}

	if !cached {
		vehicleSignalsTrackingEventsPropertyUpdateCacheMut.Lock()
		vehicleSignalsTrackingEventsPropertyUpdateCache[key] = cache
		vehicleSignalsTrackingEventsPropertyUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q vehicleSignalsTrackingEventsPropertyQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for vehicle_signals_tracking_events_properties")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for vehicle_signals_tracking_events_properties")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o VehicleSignalsTrackingEventsPropertySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), vehicleSignalsTrackingEventsPropertyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"device_data_api\".\"vehicle_signals_tracking_events_properties\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, vehicleSignalsTrackingEventsPropertyPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in vehicleSignalsTrackingEventsProperty slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all vehicleSignalsTrackingEventsProperty")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *VehicleSignalsTrackingEventsProperty) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no vehicle_signals_tracking_events_properties provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(vehicleSignalsTrackingEventsPropertyColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	vehicleSignalsTrackingEventsPropertyUpsertCacheMut.RLock()
	cache, cached := vehicleSignalsTrackingEventsPropertyUpsertCache[key]
	vehicleSignalsTrackingEventsPropertyUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			vehicleSignalsTrackingEventsPropertyAllColumns,
			vehicleSignalsTrackingEventsPropertyColumnsWithDefault,
			vehicleSignalsTrackingEventsPropertyColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			vehicleSignalsTrackingEventsPropertyAllColumns,
			vehicleSignalsTrackingEventsPropertyPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert vehicle_signals_tracking_events_properties, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(vehicleSignalsTrackingEventsPropertyPrimaryKeyColumns))
			copy(conflict, vehicleSignalsTrackingEventsPropertyPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"device_data_api\".\"vehicle_signals_tracking_events_properties\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(vehicleSignalsTrackingEventsPropertyType, vehicleSignalsTrackingEventsPropertyMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(vehicleSignalsTrackingEventsPropertyType, vehicleSignalsTrackingEventsPropertyMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert vehicle_signals_tracking_events_properties")
	}

	if !cached {
		vehicleSignalsTrackingEventsPropertyUpsertCacheMut.Lock()
		vehicleSignalsTrackingEventsPropertyUpsertCache[key] = cache
		vehicleSignalsTrackingEventsPropertyUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single VehicleSignalsTrackingEventsProperty record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *VehicleSignalsTrackingEventsProperty) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no VehicleSignalsTrackingEventsProperty provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), vehicleSignalsTrackingEventsPropertyPrimaryKeyMapping)
	sql := "DELETE FROM \"device_data_api\".\"vehicle_signals_tracking_events_properties\" WHERE \"integration_id\"=$1 AND \"device_make_id\"=$2 AND \"property_id\"=$3"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from vehicle_signals_tracking_events_properties")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for vehicle_signals_tracking_events_properties")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q vehicleSignalsTrackingEventsPropertyQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no vehicleSignalsTrackingEventsPropertyQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from vehicle_signals_tracking_events_properties")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for vehicle_signals_tracking_events_properties")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o VehicleSignalsTrackingEventsPropertySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(vehicleSignalsTrackingEventsPropertyBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), vehicleSignalsTrackingEventsPropertyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"device_data_api\".\"vehicle_signals_tracking_events_properties\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, vehicleSignalsTrackingEventsPropertyPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from vehicleSignalsTrackingEventsProperty slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for vehicle_signals_tracking_events_properties")
	}

	if len(vehicleSignalsTrackingEventsPropertyAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *VehicleSignalsTrackingEventsProperty) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindVehicleSignalsTrackingEventsProperty(ctx, exec, o.IntegrationID, o.DeviceMakeID, o.PropertyID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *VehicleSignalsTrackingEventsPropertySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := VehicleSignalsTrackingEventsPropertySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), vehicleSignalsTrackingEventsPropertyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"device_data_api\".\"vehicle_signals_tracking_events_properties\".* FROM \"device_data_api\".\"vehicle_signals_tracking_events_properties\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, vehicleSignalsTrackingEventsPropertyPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in VehicleSignalsTrackingEventsPropertySlice")
	}

	*o = slice

	return nil
}

// VehicleSignalsTrackingEventsPropertyExists checks if the VehicleSignalsTrackingEventsProperty row exists.
func VehicleSignalsTrackingEventsPropertyExists(ctx context.Context, exec boil.ContextExecutor, integrationID string, deviceMakeID string, propertyID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"device_data_api\".\"vehicle_signals_tracking_events_properties\" where \"integration_id\"=$1 AND \"device_make_id\"=$2 AND \"property_id\"=$3 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, integrationID, deviceMakeID, propertyID)
	}
	row := exec.QueryRowContext(ctx, sql, integrationID, deviceMakeID, propertyID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if vehicle_signals_tracking_events_properties exists")
	}

	return exists, nil
}
